enpitut2017/kakei_gakuen

- Gemfile.lock
- app/models/book.rb
- db/migrate/20170803041229_create_books.rb
- db/schema.rb
- test/fixtures/books.yml
- test/models/book_test.rb
> model books remake

- Gemfile
- Gemfile.lock
> add gem import

- Gemfile
- Gemfile.lock
- app/assets/javascripts/books.coffee
- app/assets/stylesheets/books.scss
- app/controllers/books_controller.rb
- app/helpers/books_helper.rb
- app/models/book.rb
- app/views/books/_book.json.jbuilder
- app/views/books/_form.html.erb
- app/views/books/edit.html.erb
- app/views/books/index.html.erb
- app/views/books/index.json.jbuilder
- app/views/books/new.html.erb
- app/views/books/show.html.erb
- app/views/books/show.json.jbuilder
- config/routes.rb
- db/migrate/20170803062959_create_books.rb
- db/schema.rb
- test/controllers/books_controller_test.rb
- test/fixtures/books.yml
- test/models/book_test.rb
- test/system/books_test.rb
> scaffoldでbooksを作り直したよ

- app/controllers/books_controller.rb
お願いします。
costsとitemsの配列が飛んで来ればオッケーです
> create contoroller 完成

- app/assets/stylesheets/books.scss
- app/models/book.rb
- app/models/user.rb
- app/views/books/_form.html.erb
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- config/routes.rb
- db/migrate/20170803155136_create_books.rb
- db/schema.rb
- test/fixtures/books.yml
とりあえずテストは通るようになりました。
原因は簡単に言うとBookのモデルとDBに最初から外部参照キーをつけなくてはいけなかったそうです。
sccafoldの場合後からhas_manyやbelong_toをつけても自動生成されたテストなどにはそのような情報がないためエラーを起こすらしいということはわかりました。
つまり初めからbookを
rails g scaffold  book item:string cost:integer user:references
のようにしてuserを外部参照するように作らないといけなかったらしいです。
(行ってしまえばuser→bookの順で作らないと自動生成の場合はだめらしい)
> fix model book and fix user controller test

- app/assets/javascripts/static_page.coffee
- app/assets/stylesheets/static_page.scss
- app/controllers/static_page_controller.rb
- app/helpers/static_page_helper.rb
- app/views/static_page/index.html.erb
- config/routes.rb
- test/controllers/static_page_controller_test.rb
> base static_page

- app/controllers/application_controller.rb
> csrf対策をとりあえずoffに

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
修正しました。user/show/において view側で
@lost の変数を呼び出すと出費
@rest の変数を呼び出すと残高
が表示されます。
> 残高および出費の計算・表示の修正

- config/routes.rb
> static_index_page_pathの修正

- app/assets/javascripts/sessions.coffee
- app/assets/stylesheets/sessions.scss
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- config/routes.rb
- test/controllers/sessions_controller_test.rb
まだ/loginが500internalServerErrorです
> login機構の追加: 途中

- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- test/controllers/sessions_controller_test.rb
> View setting

- app/controllers/books_controller.rb
とりあえず一番目のユーザーが返ってきます。
ログインができたらまた変える
> Userごとのbooksを持ってくるように変更(仮)

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- db/migrate/20170804050536_add_password_to_user.rb
- db/migrate/20170804060446_add_password_digest_to_user.rb
- db/schema.rb
> finished login

- app/controllers/books_controller.rb
> ログインユーザーごとに登録・表示ができた

- app/assets/stylesheets/custom.css
- app/views/books/index.html.erb
- app/views/books/show.html.erb
- app/views/layouts/_header.html.erb
> indexをもろもろ

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
> 最新５件の商品が表示されるようになりました

- app/views/users/show.html.erb
user/showでbooksがないときテーブルが表示されるのではなく未登録が出るようになりました
> userがbooksを所持していないとき未登録になる

- app/assets/javascripts/script.js
> Fix Books/new

- app/models/user.rb
- test/fixtures/users.yml
- test/models/user_test.rb
> ユーザーのモデルのバリデーションの変更、テストの作成

- app/assets/stylesheets/custom.css
- app/views/layouts/_footer.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
> footer をfixにした

- app/assets/javascripts/script.js
- app/views/books/_form.html.erb
> Update books/new form

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
> tutorial見ながらいろいろついか

- app/views/sessions/new.html.erb
> login画面のデザイン変更

- app/views/static_page/index.html.erb
> update to top index

- app/views/books/index.html.erb
> リンクを直して空白をいい感じに入れました

- app/views/books/index.html.erb
> ログインしてるユーザーのみのbooksを表示にしました

- app/views/books/index.html.erb
> 余計なことしたっぽい

- README.md
> Update to README.md space

- app/assets/javascripts/script.js
- app/views/layouts/application.html.erb
- app/views/sessions/new.html.erb
- app/views/users/_errors.html.erb
- app/views/users/_form.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
> 退会を確認するアラートをつけた

- config/locales/ja.yml
辞書を作りました。
今後エラーメッセージのキーを日本語化したい場合はconfig/locales/ja.ymlに追加してください
> エラーメッセージを日本語化

- app/assets/javascripts/script.js
- app/views/books/_form.html.erb
- app/views/books/new.html.erb
- app/views/layouts/_header.html.erb
> Update books view

- circl.yml
> CirclCIテスト

- circle.yml
- config/database.yml.ci
> cuirclciテスト

- circle.yml
> とりあえずawsに行くかどうか

- Scripts/AfterInstall.sh
> Test circlci

- Scripts/AfterInstall.sh
- Scripts/ApplicationStart.sh
> アセットプリコンパイルの位置を変える

- Scripts/AfterInstall.sh
> ファイルのオーナー変更

- Scripts/AfterInstall.sh
> &&の入れ忘れの修正

- Scripts/AfterInstall.sh
- Scripts/ApplicationStart.sh
- Scripts/BeforeInstall.sh
> セキュリティ強化(のよてい)

- README.md
- Scripts/AfterInstall.sh
> 初歩的なミスとawsのurlの変更

- circle.yml
- config/database.yml
- config/environments/staging.rb
- config/puma.rb
- config/secrets.yml
- setup.sh
スクリプトで起動するようにしました。
一つコマンド叩けば全部やってくれるようにしてあります。
> Setup staging

- app/controllers/users_controller.rb
- app/views/layouts/_header.html.erb
- app/views/users/show.html.erb
users/show内で買ったものが混ざる問題を解決しました
> resolve books mixing

- db/migrate/20171027074752_create_user_wearings.rb
- db/schema.rb
- test/fixtures/user_wearings.yml
> colthes -> clothes

- app/controllers/closets_controller.rb
> ユーザーの来ている服の追加

- app/controllers/users_controller.rb
- db/setup_sql.sql
> ユーザー作成時の服の設定の変更

- app/assets/javascripts/script.js
- app/views/users/show.html.erb
> recognition is back

- app/views/closets/edit.html.erb
> レイアウト崩れの修正

- app/controllers/users_controller.rb
- app/models/user.rb
> 画像登録周りの再設定

- app/views/closets/edit.html.erb
- app/views/users/show.html.erb
> 12/11 修正の追加

- app/controllers/api_controller.rb
- config/application.rb
> api接続時の商品の登録およびrails環境の時間を日本の時刻に設定

- app/assets/javascripts/closet.js
> bugfix on purchace face func

- app/controllers/api_controller.rb
- app/controllers/saves_controller.rb
- config/routes.rb
詳しくはcontroller/apiの中身を見てください。
ネイティブ周りの開発の注意として画像のurlを取得するパス(今の方法)が/api/image/path/に変わっています
> ネイティブ用画像関数のテスト

- app/assets/javascripts/script.js
- app/views/users/show.html.erb
> tooltip有効化

- app/controllers/users_controller.rb
> セリフの選択メソッド修正

- app/controllers/api_controller.rb
- config/routes.rb
> statusAPI作成

- Gemfile
- Gemfile.lock
- app/uploaders/image_uploader.rb
- app/views/users/show.html.erb
> モバイル時の画像呼び分けと生成サムネイルのサイズ変更

- app/views/users/show.html.erb
> モバイルだとTwitter共有ボタンを出さない

- app/assets/javascripts/script.js
- app/views/books/new.html.erb
> まとめて入力画面で呼ばれる関数の重複を削除

- app/controllers/api_controller.rb
ネイティブ向けサーバーから返ってくるレスポンスを大幅に修正しました
例外処理も追加しました
> レスポンス及びエラー処理の修正

- app/controllers/api_controller.rb
> 商品登録時に時間が入力できるようになる

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- config/environments/production.rb
> install google analytics
